version: 2.1

orbs:
  python: circleci/python@0.2.1
  node: circleci/node@3.0.0

jobs:
  python-style-checker:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: ./scripts/style-checker-py.sh --skip-deps
          name: Python Code Style Checker
  cpp-style-checker:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: ./scripts/style-checker-cpp.sh --skip-deps
          name: C/C++ Code Style Checker
  js-style-checker:
    executor: node/default
    steps:
      - checkout
        #      - node/install-packages:
        #          app-dir: .
      - run:
          command: npm install
      - run:
          command: ./scripts/style-checker-js.sh --skip-deps
          name: JavaScript Code Style Checker

workflows:
  style-checkers:
    jobs:
      - python-style-checker
      - cpp-style-checker
      - js-style-checker
