version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  style-checkers:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: find . -name "*.py" -not -path "./subprojects/*" -not -path "./dep/*" -not -path "./menuconfig.py" | xargs pylint --disable=fixme,import-error
          name: Code Style Checker (Python)

workflows:
  main:
    jobs:
      - style-checkers
