# This is a basic workflow to help you get started with Actions

name: Build Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: skkueslab/ant-build-test:0.1

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          find /home/ant/ -name "CMakeCache.txt" | xargs rm
          cp -r /home/ant/dep/tvm/* ./dep/tvm/
          cp -r /home/ant/dep/iotjs/* ./dep/iotjs/
          cp -r /home/ant/dep/iotivity/* ./dep/iotivity

      - name: Build ANT
        run: |
          ./scripts/build-ant.sh
