# This is a basic workflow to help you get started with Actions

name: Upload Documents

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths: [ docs/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Python version setting
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          npm install

      # Runs a set of commands using the runners shell
      - name: Run documentations
        run: |
          npm run docs:prepare
          npm run docs:build
          mkdir -p ~/ant-docs/
          cp -r ./_book/* ~/ant-docs/
          git remote -v
          git fetch origin
          git checkout origin/gh-pages -b gh-pages
          rm -rf ./*
          cp -r ~/ant-docs/* ./
          rm -rf ~/ant-docs/
          git config --local user.email "eslab-ant-docs-bot@skku.edu"
          git config --local user.name "ESLAB ANT Documentation Bot"
          git add --all
          git commit -m "Update Documentation Page" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
